### ISSUE TITLE
Crashes instantly

### ISSUE THREAD

**Issue by pseudocalm** [topher-au/HDT-Voice#3]
I really hope this can be fixed because I think this plugin would be amazing, I have tendinitis and carpal tunnel issues. I would absolutely contribute if this was working for me. 

I installed the plugin, and it crashes HDT immediately upon saying anything after enabling the plugin in the options. I enable the plugin, then pretty much say any word at all, and HDT crashes. It doesn't seem to crash until i say a word. So in this case I was in the menu and I said play. I'm using win 7 64x, and I have just properly set my mic up for speech recognition since I also use a voice program called Voice attack. I know this isn't conflicting because I just formatted windows and dont have voice attack installed yet. 
###### #### 9/2/2015 5:47:29 PM

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at HDTVoice.HDTVoice.GetProcessFilename(Int64 ProcessID)
   at HDTVoice.HDTVoice.IsHearthstoneActive()
   at HDTVoice.HDTVoice.onSpeechRecognized(Object sender, SpeechRecognizedEventArgs e)
   at System.Speech.Recognition.SpeechRecognitionEngine.SpeechRecognizedProxy(Object sender, SpeechRecognizedEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Speech.Internal.AsyncSerializedWorker.WorkerProc(Object ignored)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[5:47:03 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[5:47:03 PM] OpponentSecrets: Cleared secrets
[5:47:03 PM] DeckList: Set active deck to: Hired Tempo (Mage)
[5:47:03 PM] Tracker: Set player itemsource as PlayerDeck
[5:47:03 PM] Tracker: Switched to deck: Hired Tempo
[5:47:03 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[5:47:03 PM] OpponentSecrets: Cleared secrets
[5:47:03 PM] GameEventHandler: Reset constructed importing
[5:47:03 PM] Helper: Checking for LIVE updates...
[5:47:03 PM] Helper: Current version: 0.10.16.0
[5:47:03 PM] LogReader: Current region: US
[5:47:03 PM] UpdateOverlay: Refreshed overlay topmost status
[5:47:03 PM] BackupManager: Running BackupManager
[5:47:03 PM] BackupManager: Backup for today already exists
[5:47:03 PM] PluginManager: Loading Plugins...
[5:47:03 PM] PluginWrapper: Loading Stats Converter
[5:47:04 PM] PluginWrapper: Enabled Stats Converter
[5:47:04 PM] : Checking for duplicate matches...
[5:47:04 PM] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[5:47:04 PM] HearthStatsManager: background process indicator ON
[5:47:04 PM] HearthStatsManager: Checking HearthStats for new decks...
[5:47:04 PM] HearthStatsManager: trying to download decks
[5:47:04 PM] HearthStatsAPI: getting decks since 1441236092
[5:47:05 PM] Helper: Latest LIVE version: 0.10.16.0
[5:47:05 PM] HearthStatsManager: no new decks
[5:47:05 PM] HearthStatsManager: Checking HearthStats for new matches...
[5:47:05 PM] HearthStatsManager: trying to download games
[5:47:05 PM] HearthStatsAPI: getting games since 1441236092
[5:47:06 PM] HearthStatsManager: no new games
[5:47:06 PM] HearthStatsManager: Checking for new local decks...
[5:47:06 PM] HearthStatsManager: Checking for new local versions...
[5:47:06 PM] HearthStatsManager: Checking for edited local decks...
[5:47:06 PM] HearthStatsManager: Checking for new local matches...
[5:47:06 PM] HearthStatsManager: background process indicator OFF
[5:47:06 PM] HearthStatsManager: finished sync process
[5:47:15 PM] PluginWrapper: Loading HDT-Voice
Hearthstone Deck Tracker.exe Information: 0 : 
SAPI does not implement phonetic alphabet selection.
[5:47:15 PM] PluginWrapper: Enabled HDT-Voice
[5:47:15 PM] : Checking for HDT-Voice update...
[5:47:16 PM] : No newer version found.
[5:47:19 PM] UpdateOverlay: Refreshed overlay topmost status
[5:47:23 PM] GameEventHandler: Reset constructed importing

**Comment by topher-au** [comment]
Thankyou for your report. I'm looking into this issue right now and will push out a fix soon.
